namespace Bouncer.Rules;

public static class DefaultRuleGroups
{
    public static IReadOnlyList<RuleGroupDefinition> All { get; } =
    [
        new RuleGroupDefinition(
            "bash",
            [
                new RuleDefinition(
                    "rm-rf-root",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.RmRfRootPattern,
                    "deny",
                    "Destructive recursive delete",
                    DefaultRuleRegexes.RmRfRoot),
                new RuleDefinition(
                    "mkfs",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.MkfsPattern,
                    "deny",
                    "Filesystem format",
                    DefaultRuleRegexes.Mkfs),
                new RuleDefinition(
                    "dd-if",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.DdIfPattern,
                    "deny",
                    "Disk overwrite",
                    DefaultRuleRegexes.DdIf),
                new RuleDefinition(
                    "chmod-777",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.Chmod777Pattern,
                    "deny",
                    "Permission blowout",
                    DefaultRuleRegexes.Chmod777),
                new RuleDefinition(
                    "truncate-system-file",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.TruncateSystemFilePattern,
                    "deny",
                    "System file truncation",
                    DefaultRuleRegexes.TruncateSystemFile),
                new RuleDefinition(
                    "safe-shell-info",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.SafeShellInfoPattern,
                    "allow",
                    "Known safe shell command",
                    DefaultRuleRegexes.SafeShellInfo)
            ]),
        new RuleGroupDefinition(
            "powershell",
            [
                ..CreatePowerShellRules("pwsh")
            ]),
        new RuleGroupDefinition(
            "builtins",
            [
                new RuleDefinition(
                    "bouncer-config-write",
                    "write",
                    ToolField.Path,
                    DefaultRuleRegexes.BouncerConfigPathPattern,
                    "deny",
                    "Bouncer config modification",
                    DefaultRuleRegexes.BouncerConfigPath),
                new RuleDefinition(
                    "bouncer-config-edit",
                    "edit",
                    ToolField.Path,
                    DefaultRuleRegexes.BouncerConfigPathPattern,
                    "deny",
                    "Bouncer config modification",
                    DefaultRuleRegexes.BouncerConfigPath),
                new RuleDefinition(
                    "bouncer-hook-shim-write",
                    "write",
                    ToolField.Path,
                    DefaultRuleRegexes.BouncerHookShimPattern,
                    "deny",
                    "Bouncer hook shim modification",
                    DefaultRuleRegexes.BouncerHookShim),
                new RuleDefinition(
                    "bouncer-hook-shim-edit",
                    "edit",
                    ToolField.Path,
                    DefaultRuleRegexes.BouncerHookShimPattern,
                    "deny",
                    "Bouncer hook shim modification",
                    DefaultRuleRegexes.BouncerHookShim),
                new RuleDefinition(
                    "secret-file-write",
                    "write",
                    ToolField.Path,
                    DefaultRuleRegexes.SecretPathPattern,
                    "deny",
                    "Secret file modification",
                    DefaultRuleRegexes.SecretPath),
                new RuleDefinition(
                    "secret-file-edit",
                    "edit",
                    ToolField.Path,
                    DefaultRuleRegexes.SecretPathPattern,
                    "deny",
                    "Secret file modification",
                    DefaultRuleRegexes.SecretPath),
                new RuleDefinition(
                    "secret-file-read",
                    "read",
                    ToolField.Path,
                    DefaultRuleRegexes.SecretPathPattern,
                    "deny",
                    "Secret file access",
                    DefaultRuleRegexes.SecretPath),
                new RuleDefinition(
                    "secret-file-view",
                    "view",
                    ToolField.Path,
                    DefaultRuleRegexes.SecretPathPattern,
                    "deny",
                    "Secret file access",
                    DefaultRuleRegexes.SecretPath),
                new RuleDefinition(
                    "safe-file-write",
                    "write",
                    ToolField.Path,
                    DefaultRuleRegexes.SafeReadPathPattern,
                    "allow",
                    "Known safe file write",
                    DefaultRuleRegexes.SafeReadPath),
                new RuleDefinition(
                    "safe-file-edit",
                    "edit",
                    ToolField.Path,
                    DefaultRuleRegexes.SafeReadPathPattern,
                    "allow",
                    "Known safe file edit",
                    DefaultRuleRegexes.SafeReadPath),
                new RuleDefinition(
                    "safe-file-read",
                    "read",
                    ToolField.Path,
                    DefaultRuleRegexes.SafeReadPathPattern,
                    "allow",
                    "Known safe file read",
                    DefaultRuleRegexes.SafeReadPath),
                new RuleDefinition(
                    "safe-file-view",
                    "view",
                    ToolField.Path,
                    DefaultRuleRegexes.SafeReadPathPattern,
                    "allow",
                    "Known safe file view",
                    DefaultRuleRegexes.SafeReadPath),
                new RuleDefinition(
                    "safe-glob",
                    "glob",
                    ToolField.Pattern,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe file glob",
                    DefaultRuleRegexes.SafeNonEmpty),
                new RuleDefinition(
                    "safe-grep",
                    "grep",
                    ToolField.Pattern,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe file search",
                    DefaultRuleRegexes.SafeNonEmpty),
                new RuleDefinition(
                    "safe-todo",
                    "todo",
                    ToolField.Command,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe todo update",
                    DefaultRuleRegexes.SafeNonEmpty),
                new RuleDefinition(
                    "safe-report-intent",
                    "report_intent",
                    ToolField.ToolName,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe intent report",
                    DefaultRuleRegexes.SafeNonEmpty),
                new RuleDefinition(
                    "safe-ask-user",
                    "ask_user",
                    ToolField.ToolName,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe user prompt",
                    DefaultRuleRegexes.SafeNonEmpty),
                new RuleDefinition(
                    "safe-skill",
                    "skill",
                    ToolField.ToolName,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe skill invocation",
                    DefaultRuleRegexes.SafeNonEmpty)
            ]),
        new RuleGroupDefinition(
            "git",
            [
                new RuleDefinition(
                    "git-force-push",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.GitForcePushPattern,
                    "deny",
                    "Force push to remote",
                    DefaultRuleRegexes.GitForcePush),
                new RuleDefinition(
                    "git-reset-hard-main",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.GitResetHardPattern,
                    "deny",
                    "Hard reset on protected branch",
                    DefaultRuleRegexes.GitResetHard),
                new RuleDefinition(
                    "git-clean-fdx",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.GitCleanFdxPattern,
                    "deny",
                    "Remove untracked files",
                    DefaultRuleRegexes.GitCleanFdx),
                new RuleDefinition(
                    "git-checkout-discard",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.GitCheckoutDiscardPattern,
                    "deny",
                    "Discard working tree changes",
                    DefaultRuleRegexes.GitCheckoutDiscard),
                new RuleDefinition(
                    "safe-git-readonly",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.SafeGitReadonlyPattern,
                    "allow",
                    "Known safe git command",
                    DefaultRuleRegexes.SafeGitReadonly)
            ]),
        new RuleGroupDefinition(
            "secrets-exposure",
            [
                new RuleDefinition(
                    "secret-shell-read",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.SecretCommandPattern,
                    "deny",
                    "Secret file access via shell",
                    DefaultRuleRegexes.SecretCommand),
                new RuleDefinition(
                    "secret-curl-post",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.SecretCurlPattern,
                    "deny",
                    "Secret content exfiltration",
                    DefaultRuleRegexes.SecretCurl)
            ]),
        new RuleGroupDefinition(
            "production-risk",
            [
                new RuleDefinition(
                    "curl-delete-prod",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.CurlDeleteProdPattern,
                    "deny",
                    "Production DELETE request",
                    DefaultRuleRegexes.CurlDeleteProd),
                new RuleDefinition(
                    "db-drop-truncate",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.DbDropTruncatePattern,
                    "deny",
                    "Destructive database command",
                    DefaultRuleRegexes.DbDropTruncate),
                new RuleDefinition(
                    "kubectl-delete-prod",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.KubectlDeleteProdPattern,
                    "deny",
                    "Kubernetes delete in production namespace",
                    DefaultRuleRegexes.KubectlDeleteProd),
                new RuleDefinition(
                    "kubectl-apply-no-dryrun",
                    "bash",
                    ToolField.Command,
                    DefaultRuleRegexes.KubectlApplyNoDryRunPattern,
                    "deny",
                    "Kubernetes apply without dry-run",
                    DefaultRuleRegexes.KubectlApplyNoDryRun)
            ]),
        new RuleGroupDefinition(
            "web",
            [
                new RuleDefinition(
                    "webfetch-paste",
                    "web_fetch",
                    ToolField.Url,
                    DefaultRuleRegexes.WebFetchPastePattern,
                    "deny",
                    "Potential secret exfiltration",
                    DefaultRuleRegexes.WebFetchPaste),
                new RuleDefinition(
                    "safe-webfetch",
                    "web_fetch",
                    ToolField.Url,
                    DefaultRuleRegexes.SafeWebFetchPattern,
                    "allow",
                    "Known safe web fetch",
                    DefaultRuleRegexes.SafeWebFetch),
                new RuleDefinition(
                    "safe-websearch",
                    "web_search",
                    ToolField.Query,
                    DefaultRuleRegexes.SafeNonEmptyPattern,
                    "allow",
                    "Known safe web search",
                    DefaultRuleRegexes.SafeNonEmpty)
            ])
    ];

    private static IEnumerable<RuleDefinition> CreatePowerShellRules(string toolName) =>
    [
        new RuleDefinition(
            $"{toolName}-remove-item-root",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellRemoveItemRootPattern,
            "deny",
            "Destructive recursive delete",
            DefaultRuleRegexes.PowerShellRemoveItemRoot),
        new RuleDefinition(
            $"{toolName}-remove-item-systemroot",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellRemoveItemSystemRootPattern,
            "deny",
            "System directory delete",
            DefaultRuleRegexes.PowerShellRemoveItemSystemRoot),
        new RuleDefinition(
            $"{toolName}-disk-wipe",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellDiskWipePattern,
            "deny",
            "Disk formatting or wipe",
            DefaultRuleRegexes.PowerShellDiskWipe),
        new RuleDefinition(
            $"{toolName}-execution-policy-bypass",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellExecutionPolicyBypassPattern,
            "deny",
            "Execution policy bypass",
            DefaultRuleRegexes.PowerShellExecutionPolicyBypass),
        new RuleDefinition(
            $"{toolName}-invoke-expression",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellInvokeExpressionPattern,
            "deny",
            "Dynamic expression execution",
            DefaultRuleRegexes.PowerShellInvokeExpression),
        new RuleDefinition(
            $"{toolName}-registry-delete",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellRegistryDeletePattern,
            "deny",
            "Registry delete",
            DefaultRuleRegexes.PowerShellRegistryDelete),
        new RuleDefinition(
            $"{toolName}-stop-restart",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellStopRestartPattern,
            "deny",
            "System shutdown or restart",
            DefaultRuleRegexes.PowerShellStopRestart),
        new RuleDefinition(
            $"{toolName}-safe-info",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellSafeInfoPattern,
            "allow",
            "Known safe PowerShell command",
            DefaultRuleRegexes.PowerShellSafeInfo),
        new RuleDefinition(
            $"{toolName}-safe-read",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.PowerShellSafeReadPattern,
            "allow",
            "Known safe PowerShell file read",
            DefaultRuleRegexes.PowerShellSafeRead),
        new RuleDefinition(
            $"{toolName}-safe-shell-alias",
            toolName,
            ToolField.Command,
            DefaultRuleRegexes.SafeShellInfoPattern,
            "allow",
            "Known safe shell command",
            DefaultRuleRegexes.SafeShellInfo)
    ];
}
